language: node_js
node_js:
  - 'node'
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
env:
  - EXTENSION_ID=pjkolicadkdcfgjjoopdpleenckeajkk
deploy:
  provider: script
  skip_cleanup: true
  script: yarn run release
  on:
    branch: master
    tags: true
# allow headful tests
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
